### ISSUE TITLE
Example command

### ISSUE THREAD

**Issue by srilaxmi-kanna** [cherryleafroad/Android-ImageMagick7#10]
Thanks so much for this contribution!!

I have everything compiling and would like to use the binary. How would I call a command? 

In `Process proc = Runtime.getRuntime().exec(cmd, ENV);`

Could you give me an example of what the `cmd` parameter should look like?

**Comment by cherryleafroad** [comment]
Please refer to the [binary section in the readme](https://github.com/cherryleafroad/Android-ImageMagick7#how-to-run-the-binary) on the main page.

The [example app](https://github.com/cherryleafroad/Android-ImageMagick7/tree/master/libjmagick-7/android/app) has all the code you need to put together a working copy.

You can find example code for calling the binary in the [example apps MainActivity.java](https://github.com/cherryleafroad/Android-ImageMagick7/blob/master/libjmagick-7/android/app/src/main/java/com/example/project/MainActivity.java)

**Comment by srilaxmi-kanna** [comment]
Got it, thanks

**Comment by cherryleafroad** [comment]
Good luck! If you have any more questions, feel free to ask ;)
