### ISSUE TITLE
How to use Cipher in Android?

### ISSUE THREAD

**Issue by hvsimon** [cherryleafroad/Android-ImageMagick7#11]
I have used the keyword "cipher" to search but nothing related to Java.
Does it support [Encipher or Decipher an Image](https://imagemagick.org/script/cipher.php) in Android project?

**Comment by cherryleafroad** [comment]
The build scripts will build the binary. After that, you just need to setup the binary using the example project, then execute the binary using the same command-line flags you saw in their examples.
Please see the [process code here](https://github.com/cherryleafroad/Android-ImageMagick7/blob/4bd04c2facf279d56cb5d1d5fd18c138f018f8a2/libjmagick-7/android/app/src/main/java/com/example/project/MainActivity.java#L317)

Cipher is [listed](https://github.com/cherryleafroad/Android-ImageMagick7#android-imagemagick-709-17) as one of the default build features, so as long as you have everything setup properly, just execute it as you would any other CLI program
