### ISSUE TITLE
Help needed to generate .so file in GitHub Actions

### ISSUE THREAD

**Issue by malaythecool** [cherryleafroad/Android-ImageMagick7#12]
I am trying to automate the build to create .so file on the go. 
I have tried the ways you described in the instruction but still unable to figure out the generating of .so file due to some c++ errors.
It would be great if you can take a look at the build failures and suggest the changes that I might have missed!

https://github.com/malaythecool/Android-ImageMagick7/runs/2363995707?check_suite_focus=true

**Comment by cherryleafroad** [comment]
Try the steps in this issue:
https://github.com/cherryleafroad/Android-ImageMagick7/issues/9#issuecomment-748531617

**Comment by malaythecool** [comment]
Thanks for the appropriate suggestion, really appreciated your quick response. It started working in my local machine and soon I might able to run it on GitHub action to ease of access to the people looking to download direct .so files on new releases!

**Comment by cherryleafroad** [comment]
If you have any changes/improvements, please do issue a pull request!! Auto github building would be a godsend (I'm not sure how to set it up right now)

**Comment by malaythecool** [comment]
I'll surely do PR once I built it successfully in my fork after experiments!

**Comment by malaythecool** [comment]
> 
> 
> Try the steps in this issue: [#9 (comment)](https://github.com/cherryleafroad/Android-ImageMagick7/issues/9#issuecomment-748531617)
> 
> If that doesn't resolve it, it seems to be that the newer NDK isn't supported (sadly I've been busy and don't have the time to test compatibility with the newer NDK). I suggest to try the one before 22
> 
> P.P.S. Old build [here](https://github.com/cherryleafroad/Android-ImageMagick7/issues/4#issuecomment-568859199), although it's not the latest however

I tried to build that and got only following files generated:
1. libc++_shared.so
2. libomp.so
3. magick

Instead of the libs I found from your static prebuild:
1. libc++_shared.so
2. libjmagick-7.so
3. libmagickcore-7.so
4. libmagickwand-7.so

Can you point if I did missed anything in configuration?

**Comment by cherryleafroad** [comment]
You didn't miss anything. If you see things built successfully, then you did it right. From what I see, it looks like you did a static build  without libs (which means you wouldn't see any anyways).

As for the jmagick, you probably have that disabled, which is recommended to keep it disabled (jmagick is old, buggy, and unsupported, so it's better to just use it straight from the CLI)

**Comment by malaythecool** [comment]
I have created a PR.
Once merged you can go to Actions Tab > Release > Run workflow to create artifacts.
