### ISSUE TITLE
Unable to save images

### ISSUE THREAD

**Issue by mohit67890** [cherryleafroad/Android-ImageMagick7#14]
Hi, 

This is really a great library. 
However, I'm trying to save the image in my gallery path wherein the new path is provided. 
image.write(ImageInfo) is not saving any image to gallery. 

Also, there seemed to be missing functions of converting image to Bitmap.

It would be great if you can help me in that..

Regards,
Mohit

**Comment by cherryleafroad** [comment]
> Also, there seemed to be missing functions of converting image to Bitmap.

Well, first of all, I'm not sure if there is or isn't a way to do that. There may be, but I haven't dealt with jmagick that much anymore. Second of all, if it is indeed missing, the reason why would be that the [official jmagick library](https://github.com/techblue/jmagick) is old, out of date, and largely unmaintained. This is why in the FAQ I suggest to never use jmagick, as any problems you encounter, missing features, will have no support (and you're likely to encounter them). Binary usage is your best option here.

> However, I'm trying to save the image in my gallery path wherein the new path is provided.

Try to check out [the jmagick examples](https://github.com/cherryleafroad/Android-ImageMagick7/blob/052c9a37a026af175b3b037849e6d244de5766da/libjmagick-7/android/app/src/main/java/com/example/project/MainActivity.java#L174) if that helps. Have you also tried to [follow the general structure](https://github.com/cherryleafroad/Android-ImageMagick7/blob/052c9a37a026af175b3b037849e6d244de5766da/libjmagick-7/android/app/src/main/java/com/example/project/MainActivity.java#L93) of the example?

**Comment by mohit67890** [comment]
Hey, Thanks for the reply.. 

Yes, the old jmagick library have support for conversion to bitmap and vice versa. 
I have tried the same function with your library but it seems to be not working...

I have two main questions:
1. Does this library works for png as well because when there is transparency, I'm facing some issues. 
2. How do I save Image to galley.. 

I have tried Boolean save = image.writeImage with new path of the gallery. 
However, the image is not getting saved.. 

Can you please help me in that.. 

Also, can you help me here by contacting on either:
telegram - @mohit67890
skype - live:mohit.garg67890

I am trying to build something since last three days but failing to do so.. 

Regards,
Mohit

**Comment by cherryleafroad** [comment]
The reason jmagick has problems with these things is that they never updated it to support all the features and code of the newer imagemagick versions. Since they have to use the c code api, it gets very specific, and if they don't do things according to the way imagemagick works now it causes these issues.

So, assuming you are doing it right, my suggestion here is to not use jmagick at all, but use the binary. There's all kinds of issues everywhere because of code incompatibility

**Comment by mohit67890** [comment]
Hi, I am not using jmagick at all.. Im using the same library as you have in the first section in your MainActivity.java file...
Also, in relation to Android >= 10. I already have 
android:requestLegacyExternalStorage="true" in AndroidManifest.xml

I am just saying it in the pictures gallery. Also, it works fine with Open CV, I can save image through that.. 
There seems to be a case in this part only.. 

I can share you the code I'm trying for you to test though..

**Comment by cherryleafroad** [comment]
`image.write(ImageInfo)` this is jmagick specific code.

If you're not using jmagick, please check the [commented sections](https://github.com/cherryleafroad/Android-ImageMagick7/blob/197fee6cc49a507a590df6dbc78075ba69b4b2ea/libjmagick-7/android/app/src/main/java/com/example/project/MainActivity.java#L29) in the example for binary only usage.

[Here](https://github.com/cherryleafroad/Android-ImageMagick7/blob/197fee6cc49a507a590df6dbc78075ba69b4b2ea/libjmagick-7/android/app/src/main/java/com/example/project/MainActivity.java#L29) and [here](https://github.com/cherryleafroad/Android-ImageMagick7/blob/197fee6cc49a507a590df6dbc78075ba69b4b2ea/libjmagick-7/android/app/src/main/java/com/example/project/MainActivity.java#L215)

Make sure to delete the uncommented jmagick section as well

**Comment by mohit67890** [comment]
Okay, I have loaded the library correctly as was in the commented section.. 
The reason I skipped the Async Task was that I didn't get reference to Share Activity and you are getting info from external preferences.. 
Can you provide me String literals on how to run command because there is no Share Activity reference that I can find and hence it is difficult to get to know as to how to run command through that...

It would be better if you can explain the same as like that of an imagemagick command line..

**Comment by cherryleafroad** [comment]
Solved elsewhere
