### ISSUE TITLE
if anybody compil please share apk 

### ISSUE THREAD

**Issue by fob014** [cherryleafroad/Android-ImageMagick7#15]
if anybody compil please share apk

**Comment by cherryleafroad** [comment]
There are some [old releases](https://github.com/cherryleafroad/Android-ImageMagick7/releases). There's also a prebuilt [binary](https://github.com/cherryleafroad/Android-ImageMagick7/tree/master/libjmagick-7/android/app/src/main/assets) and [lib](https://github.com/cherryleafroad/Android-ImageMagick7/tree/master/libjmagick-7/android/app/libs/arm64-v8a) in the examples folder. Of course, they're outdated compared to the project source, but it's something right?

**Comment by fob014** [comment]
but it doesn't have apk 
how to get apk of it

**Comment by cherryleafroad** [comment]
This is an Android library for building your own app and using ImageMagick in it. An apk would do no good for you (there'd be nothing to even show). If you'd like to use this library, feel free to check the main page which lists instructions on how to use it within Android and Java (along with an example app you can take code from and put in yours*).

* Don't use the example app code verbatim, as it's not meant to be a complete app. It's meant for you to take the needed code from it, change it as needed, and put it into your own app.
