### ISSUE TITLE
Rewrite jmagick library

### ISSUE THREAD

**Issue by cherryleafroad** [cherryleafroad/Android-ImageMagick7#2]
It's outdated, old, and buggy. Also, the API isn't very modern anymore, and doesn't fit well with imagemagick features.

**Comment by cherryleafroad** [comment]
About 60% through rewriting the whole API, but it's too much work right now. I don't have time to complete it.

**Comment by f1vefour** [comment]
You have done an excellent job here. What was your goal for this project? A full featured Android application or just a image manipulation library?

**Comment by cherryleafroad** [comment]
Just a usable image manipulation library, which can be used from Java as well

**Comment by yusrilmr** [comment]
Hi, 

Currently, I am looking for a library to manipulate images (draw and add text) and based on the [website](https://imagemagick.org/), it seems ImageMagick will cover all features that I need.
However, I am not familiar with ImageMagick and I am not an expert in Android development. 

To the best of my knowledge, to include an external library into your project, you have to find the ".jar" file first. I have tried to find it within your [repository](https://github.com/cherryleafroad/Android-ImageMagick7), but I could not find any.

I believe it's more because of my limited knowledge. Therefore, Would you like to show me how to properly include ImageMagick library to an Android Project?

Thank you in advance.

**Comment by cherryleafroad** [comment]
@yusrilmr You can use the java source code in [libjmagick-7/android/magick](libjmagick-7/android/magick)

**Comment by cherryleafroad** [comment]
I don't have time to do an entire API conversion to Java, so I'll have to close this one

**Comment by cherryleafroad** [comment]
This is done now with KMagick. #45

**Comment by CrackerKSR** [comment]
I have been trying hard to implement jmagick-6.3.9 but could not. Then came to know that you have this here. I want to use ImageMagick in react native for resiing and converting the animated webp files only I am very noob in android studio. I could not implement this library into a React Native node_module although I was able to implement some other libraries using maven. 
I tried puting .so files and set up build.gradle like given in example. Could not implement. I am sitting hopeless as I can't learn all those things right and. My app stuck at the end as I am not able to manipulate animated webp files.

**Comment by cherryleafroad** [comment]
> I have been trying hard to implement jmagick-6.3.9 but could not. Then came to know that you have this here. I want to use ImageMagick in react native for resiing and converting the animated webp files only I am very noob in android studio. I could not implement this library into a React Native node_module although I was able to implement some other libraries using maven. 
> I tried puting .so files and set up build.gradle like given in example. Could not implement. I am sitting hopeless as I can't learn all those things right and. My app stuck at the end as I am not able to manipulate animated webp files.  

Jmagick is old and incompatible with the new imagemagick 7. It needs a complete rewrite to work. While I did make it "work" by patching it, it was buggy and inconsistent at best, and at worst didn't even do what you wanted it to do. So I do not suggest even bothering trying with it.

Regarding the imagemagick .so. it is only imagemagick and nothing more. It has no bindings in it to java.

Why don't you check kmagick which was make using (the much better) kotlin?
https://github.com/cherryleafroad/kmagick

**Comment by CrackerKSR** [comment]
I can resize the _animated webp_ files on ImageMagick 7 **windwos cli**. So can I do that with kmagick? If so then I will try to create a React Native module using kmagick. 
Currently only static image resizing is avaialble for React Native and also there is a RN module of ffmpeg but cannot resize or convert animated webp as no webp decoder avaialble there.  After resolving my problem I will make the RN module public so that other wont have to suffer like me.

**Comment by cherryleafroad** [comment]
> I can resize the _animated webp_ files on ImageMagick 7 **windwos cli**. So can I do that with kmagick? If so then I will try to create a React Native module using kmagick. 
> Currently only static image resizing is avaialble for React Native and also there is a RN module of ffmpeg but cannot resize or convert animated webp as no webp decoder avaialble there.  After resolving my problem I will make the RN module public so that other wont have to suffer like me.

Check the main page for the information you need. WebP delegate is enabled. If kmagick doesn't serve your needs, you can try using the binary directly. Both the library and binary are present for this reason

**Comment by CrackerKSR** [comment]
I tried to setup kotline and I can import the ```com.cherryleafroad.kmagick.*``` . but when I use Magick.initialize() the app crash on invoking.  It seems that I could not place the jars and so files properly or missed some configs like Loading library in constructor or somthing else.

It would be easy if kotline sample project were there like where to put so and jars and what to write in build.gradle and if there is more neccesary config required before using Magick . :(

**Comment by CrackerKSR** [comment]
> > I can resize the _animated webp_ files on ImageMagick 7 **windwos cli**. So can I do that with kmagick? If so then I will try to create a React Native module using kmagick.
> > Currently only static image resizing is avaialble for React Native and also there is a RN module of ffmpeg but cannot resize or convert animated webp as no webp decoder avaialble there.  After resolving my problem I will make the RN module public so that other wont have to suffer like me.
> 
> Check the main page for the information you need. WebP delegate is enabled. If kmagick doesn't serve your needs, you can try using the binary directly. Both the library and binary are present for this reason

I tried to setup kotline and I can import the ```com.cherryleafroad.kmagick.*``` . but when I use Magick.initialize() the app crash on invoking.  It seems that I could not place the jars and so files properly or missed some configs like Loading library in constructor or somthing else.

It would be easy if kotline sample project were there like where to put so and jars and what to write in build.gradle and if there is more neccesary config required before using Magick . :(

**Comment by CrackerKSR** [comment]
> > I can resize the _animated webp_ files on ImageMagick 7 **windwos cli**. So can I do that with kmagick? If so then I will try to create a React Native module using kmagick.
> > Currently only static image resizing is avaialble for React Native and also there is a RN module of ffmpeg but cannot resize or convert animated webp as no webp decoder avaialble there.  After resolving my problem I will make the RN module public so that other wont have to suffer like me.
> 
> Check the main page for the information you need. WebP delegate is enabled. If kmagick doesn't serve your needs, you can try using the binary directly. Both the library and binary are present for this reason

Well I am not using Android Studio but the CLI and trying to implement directly in React Native. Now I will try kmagick on Android Studio and fix there first then will bring it to react native. :) btw Thanks for guiding.
