### ISSUE TITLE
Confused between Static and Shared. 

### ISSUE THREAD

**Issue by shockergit** [cherryleafroad/Android-ImageMagick7#58]
Which version should in install. Whats the difference between both please tell.

**Comment by cherryleafroad** [comment]
Static is a binary. Use the binary if you'd rather work with a binary.
Usually these are easier to setup and use. You have to execute the binary a
certain way with certain env vars.

Shared are shared object libraries (.so files). You can use those if you
need a shared object for some reason, if you want to create your own
imagemagick bindings using c++, rust, or whatever, OR if you wanna try out
my new Kotlin imagemagick bindings.

All instructions and tutorials are on the main page.

**Comment by shockergit** [comment]
Can you make a apk version also with some basic features.

**Comment by cherryleafroad** [comment]
Everything you need to know is in the instructions. There's even an example
Android app with code linked to on the main page.

**Comment by shockergit** [comment]
Sorry to say i couldn't find the apk. Can you post the link

**Comment by cherryleafroad** [comment]
What is your purpose for using this?

This is a developer library to integrate imagemagick into your own Android apps. It's for programming your own custom app. An apk would serve no purpose whatsoever.

If you want to see example code and instructions, the link is on the main page in the tutorial, and you can find everything you need to know and how it works there.

https://github.com/cherryleafroad/Android-ImageMagick7/tree/master/example-app/android/app

**Comment by shockergit** [comment]
Ok sorry i thought it was a apk port of imagemagick to android

**Comment by cherryleafroad** [comment]
Is this issue resolved, or do you have any further questions?

**Comment by shockergit** [comment]
Nothing sir
