### ISSUE TITLE
I saw your "build.gradle" file and added lines. I can clearly see libc++_shared.so under "data/app/package/lib/arm64/" directory. Is that the right path where the lib should be present?

### ISSUE THREAD

**Issue by rupesh-kumar-lpu** [cherryleafroad/Android-ImageMagick7#6]
I saw your "build.gradle" file and added lines. I can clearly see libc++_shared.so under "data/app/package/lib/arm64/" directory. Is that the right path where the lib should be present?
I tried to execute the cmd using env as follows-
```
ArrayList<String> env = new ArrayList<>();
        env.add("TMPDIR=" + file.getAbsolutePath()+"/");
        env.add("MAGICK_HOME=" + getFilesDir().getAbsolutePath()+"/usr/");
        env.add("ICU_DATA_DIR_PREFIX=" +getFilesDir().getAbsolutePath()+"/usr/");
        env.add("LD_LIBRARY_PATH=" + this.getApplicationInfo().nativeLibraryDir);
        for (Map.Entry<String, String> entry : System.getenv().entrySet()) {
            env.add(entry.getKey() + "=" + entry.getValue());
        }
        String[] ENV = env.toArray(new String[0]);
        try {
            Process proc = Runtime.getRuntime().exec(ed, ENV);
        } catch (IOException e) {
            e.printStackTrace();
            Toast.makeText(this,"catch run",Toast.LENGTH_SHORT).show();
        }
```
I am getting the null pointer exception as
```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
        at com.iamtrk.imagemagicktest.MainActivity.executecommand(MainActivity.java:121)
        at com.iamtrk.imagemagicktest.MainActivity$1.onClick(MainActivity.java:66)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22462)
        at android.os.Handler.handleCallback(Handler.java:754)
```
But I can see the env defined folders are at proper location by device manager of android studio.
Thanks

_Originally posted by @rupesh-kumar-lpu in https://github.com/cherryleafroad/Android-ImageMagick7/issues/5#issuecomment-574461602_

**Comment by rupesh-kumar-lpu** [comment]
please have a look at the main activity. I made it small and easy to understand 
<https://drive.google.com/open?id=15_zX4OHGqVicpBavuzsVtRBrAwP56vMj>
Waiting for your reply.
Thanks

**Comment by rupesh-kumar-lpu** [comment]
By mistake I created new issue and your previous comments got erased sorry for that.

**Comment by cherryleafroad** [comment]
Looks like you forgot to use `Context`. See the [Android docs](https://developer.android.com/reference/android/content/Context.html#getFilesDir()).

**Comment by rupesh-kumar-lpu** [comment]
Hi @cherryleafroad ,
It's helpful that you advised me to use Async Task as my UI was freezing up previously while executing some other binaries. If I talk about my project, I am trying to integrate your main activity code into my main activity java file and I am getting a lot of exceptions that I can share. But It would be more helpful If you can provide me a proper android studio example project with all the necessary gradle files. I can understand you may be having your schedule but it would be easier for you, please try to share if possible. If you can just provide a project which can pass command and show output on the textview. 
Thanks again!
Rupesh

**Comment by rupesh-kumar-lpu** [comment]
You can contact me at rk1307825@gmail.com thanks

**Comment by cherryleafroad** [comment]
>But It would be more helpful If you can provide me a proper android studio example project with all the necessary gradle files.

The necessary gradle files are already provided in the example app.

>If I talk about my project, I am trying to integrate your main activity code into my main activity java file and I am getting a lot of exceptions that I can share.

My code is not meant to work out of the box. It is meant to serve as an example with enough detail to give you a head start to adapt it to your needs without needing to do so much extensive research through the Android docs. Java and Android knowledge is still required to understand it and adapt it to your needs.  If you need additional help with Java programming exceptions, running binaries using Java / Android, or just Java in general please check the appropriate [Android Docs](https://developer.android.com/reference/packages), [Java Docs](https://docs.oracle.com/javase/7/docs/api/), or Google / StackOverflow. I also recommend you to join a AndroidDev discord as these people can help you with general Android programming.

With the help of these other resources, including cross-referencing the Android example app code, the Quick Setup Instructions on the main page, and the FAQ, should allow you to recreate a working copy using the binary and/or libraries.
