### ISSUE TITLE
Missing some class definitions

### ISSUE THREAD

**Issue by carloseustaquio** [cherryleafroad/Android-ImageMagick7#69]
Hey, I'm trying to integrate this with my app, I'm reusing the code from the `example-app` and converting it to Kotlin. I'm very confused though about this `ShareActivity` that appears on the `ProcessImageTask` constructor. I see that you're passing the `MainActivity` context to it, but I don't see where this `ShareActivity` is being defined. Also, I don't see the definition for the `FileUtils` and `IOUtils`.

https://github.com/cherryleafroad/Android-ImageMagick7/blob/2c6d3f363446d1898b65d73ead48e66d6998a39c/example-app/android/app/src/main/java/com/example/project/MainActivity.java#L112

https://github.com/cherryleafroad/Android-ImageMagick7/blob/2c6d3f363446d1898b65d73ead48e66d6998a39c/example-app/android/app/src/main/java/com/example/project/MainActivity.java#L68

**Comment by cherryleafroad** [comment]
`IOUtils` and `FileUtils` can both be found with `implementation 'commons-io:commons-io:2.6'` in your build.gradle.

`org.apache.commons.io.FileUtils`
`org.apache.commons.io.IOUtils`

`ShareActivity` can be replaced with whatever class is relevant to you (that's your own implementation for your app, so it's not important)

**Comment by carloseustaquio** [comment]
Nice!
I'll add the `commons-io` to my gradle config.
Hum, ok... I thought that this ShareActivity was part of the setup process.
Well, the Kotlin bindings are awesome, I was using them until I realized that my project needs to be multiplatform. I'll have an ios app in the future and I'm planning to reuse my ImageMagick scripts on both apps. That'll probably be a hybrid app actually... ReactNative or Flutter maybe.

**Comment by cherryleafroad** [comment]
I see! Wish you good luck! 💯

**Comment by carloseustaquio** [comment]
Thanks!

Could you help me with one last thing?
I finished the setup and all the files are in place.  However, I'm getting some Access Denied errors, like:

`java.io.IOException: Cannot run program "/data/user/0/com.example.myapp/files/usr/bin/arm64-v8a/magick": error=13, Permission denied`

I saw on the [docs](https://github.com/cherryleafroad/Android-ImageMagick7#solution-1---run-the-elf-binary-from-the-native-libs-directory) that this is a known error. But I couldn't understand how I should call the binary in the solution 1 approach

This is how I'm trying to run the binary. For instance, I'm just trying to print the version `Runtime.getRuntime().exec("$magickPath --version", ENV)`

```kt
class MainActivity : AppCompatActivity() {
    private val TAG = "main-activity"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        Log.i(TAG, "onCreate run")
        setContentView(R.layout.activity_main)
        setupMagick()
    }

    private fun setupMagick() {
        /* Obviously you will need to check whether you already set this up or not
           You don't want to run this every time you start your app
           You can use Android SharedPrefs to keep track of it */

        val files = arrayOf(
            "usr", "tmp"
        )

        // check for and copy over assets
        AppInitializer.copyAssets(this, files)

        // make sure executable bit is set
        val arch: String = Build.SUPPORTED_ABIS.get(0)
        val binDir = filesDir.absolutePath.toString() + "/usr/bin/" + arch + "/"
        val magickPath = binDir + "magick"

        AppInitializer.setExecutableBit(magickPath)

        // create magick symlinks. Used for different functions in magick
        // check imagemagick docs for more info
        val symlinks = arrayOf(
            "animate", "compare", "composite",
            "conjure", "convert", "display",
            "identify", "import", "magick-script",
            "mogrify", "montage", "stream"
        )

        try {
            for (symlink in symlinks) {
                AppInitializer.createSymbolicLink(magickPath, binDir + symlink)
            }
        } catch (e: ErrnoException) {
            val msg: CharSequence = "Failed to create symlinks"
            Toast.makeText(this, msg, Toast.LENGTH_LONG).show()

            // cleanup
            try {
                for (file in files) {
                    val f = File(filesDir.absolutePath.toString() + "/" + file)
                    if (f.isDirectory) {
                        f.deleteRecursively()
                    } else {
                        f.delete()
                    }
                }
            } catch (a: IOException) {
                val msgs: CharSequence = "Failed to delete a file or folder on reset"
                Toast.makeText(this, msgs, Toast.LENGTH_LONG).show()
            }
        }

        // get some uri file stream from an intent, send it to AsyncTask for further processing
        val intent: Intent = intent
        val uri: Uri? = intent.getParcelableExtra("EXTRA_STREAM")

        Thread(Runnable {
            val usrDir = "${filesDir.path}/usr"
            val tmpDir = "${filesDir.path}/tmp"
            val env: ArrayList<String> = ArrayList()
            env.add("TMPDIR=$tmpDir")
            env.add("MAGICK_HOME=$usrDir")
            env.add("ICU_DATA_DIR_PREFIX=$usrDir")
            env.add("LD_LIBRARY_PATH=${applicationInfo.nativeLibraryDir}")
            for (entry in System.getenv().entries) {
                env.add(entry.key.toString() + "=" + entry.value)
            }
            val ENV: Array<String> = env.toArray(arrayOfNulls(0))
            val proc = Runtime.getRuntime().exec("$magickPath --version", ENV)
            proc.waitFor()
        }).start()
    }
}
```

**Comment by cherryleafroad** [comment]
You know where you place all the libs (`.so` files)? Place the binary there instead and rename it something like 'libmagickbinary.so`. Then get the path to the native lib folder using the Android api and execute the "lib".

**Comment by carloseustaquio** [comment]
Ok, thanks!
