### ISSUE TITLE
please add it to f-droid

### ISSUE THREAD

**Issue by 3j9fkyahunqoxwqu** [cherryleafroad/Android-ImageMagick7#7]
Hello
Thank you for this great work.
may you please add this to F-droid?
Thank you very much.

**Comment by cherryleafroad** [comment]
F-droid is for apps. This is a library to use in building your own apps.

**Comment by 3j9fkyahunqoxwqu** [comment]
Oh, I see.
Thank you very much

**Comment by cherryleafroad** [comment]
Did you need any help with something specific? What are your needs?

**Comment by 3j9fkyahunqoxwqu** [comment]
Thank you.
it was not very related to programming, i wanted to convert large resolution pictures with low ppi density to smaller ones with higher density and searched to find something helpful (or even can this happen) but i couldn't find useful info.

Thank you very much.

**Comment by cherryleafroad** [comment]
Are you needing to run that on Android? If not, you can use the main Imagemagick program for PC.

**Comment by 3j9fkyahunqoxwqu** [comment]
Oh, Thank you very much. @
