### ISSUE TITLE
convert heif to png

### ISSUE THREAD

**Issue by tumuyan** [cherryleafroad/Android-ImageMagick7#79]
I use magick for Windows, (ImageMagick-7.1.0-portable-Q16-x64), it could convert heif to png.
But your build could not do this work, just print error:
```
magick: NoDecodeDelegateForThisImageFormat `HEIF' @ error/constitute.c/ReadImage/738.
```

So how to build a elf file to convert heif/heic to png?

**Comment by cherryleafroad** [comment]
I believe that the libheif delegate is not supported right now for this build.
See: https://github.com/strukturag/libheif

**Comment by tumuyan** [comment]
Is it cause of here are some problems with libheif , or for some other reason in magick?
If you are working with libheif, when maybe it release?

Thanks

**Comment by tumuyan** [comment]
Is the work just like  8d8711270e579e8f438d83daaf5e9e9ba624e2c2 ? 
I would  pull libheif and have a try

**Comment by cherryleafroad** [comment]
It's similar yes.

The steps generally involve:
1: Copy the lib source to a folder.
2: Create a mk file for it. Include all source files to compile. Make sure variables like enable variables, static/shared flags work for it (you can see the other mk files for reference)
3: Add an entry in the libmagickcore mk file where you define the proper imagemagick delegate define for that lib. There may be several other entries to do. You can copy imagemagick source and do a ./configure, and look at the generated `magick_baseconfig.h` to get some ideas ([there should also be a local copy here](https://github.com/cherryleafroad/Android-ImageMagick7/tree/master/ImageMagick-7.1.0-36/configs/arm64/MagickCore)).
4: of course, put the make file in the master mk file Android.mk/Application.mk

To make sure the lib actually compiles though, you will need to set up the Android ndk environment, which is basically the Building from source section in the [FAQ](https://github.com/cherryleafroad/Android-ImageMagick7#building-from-source=)

**Comment by tumuyan** [comment]
I have tried, but found it is difficult for me. 
The easy way is use Android API to pre-process the image to bitmap or png

**Comment by cherryleafroad** [comment]
That is one workable solution! Glad you found a decent way at least 🙂
