### ISSUE TITLE
OpenMP ../jniLibs/arm64-v8a/libomp.so: Error while running build-release command windows 10

### ISSUE THREAD

**Issue by androsparks** [cherryleafroad/Android-ImageMagick7#8]
[arm64-v8a] OpenMP ../jniLibs/arm64-v8a/libomp.so:
The system cannot find the path specified.
make: *** [C:/Android/sdk/ndk-bundle/build//../build/core/openmp.mk:46: ../jniLibs/arm64-v8a/libomp.so] Error 1
make: *** Waiting for unfinished jobs....
[arm64-v8a] Compile        : magick <= magick.c 

@cherryleafroad can you help please. 

I  am following the steps,
1. Created a new  empty android studio project
2. Copied android sources to the created project 
3. Copied libOpenCl.so from device to the jniLibs folder 
4. But when i running build-release command, i am getting the above error.

My Project Structure is,

 
![project structure](https://user-images.githubusercontent.com/46017420/93453526-6ac30e00-f8f7-11ea-89c9-ba119275d8ba.png)

**Comment by androsparks** [comment]
My Bad,
Changed OpenMP to OpenCL.
Also moved libOpenCl.so inside libopencl\qualcomm\lib\64 folder.
Able to build now. Thanks

**Comment by cherryleafroad** [comment]
@androsparks  I'm really happy to hear that the problem was resolved for you!

**Comment by androsparks** [comment]
@cherryleafroad 
Thanks 👍 I just need to convert images from one format to another (Between all the formats).
Any tips for me to build armeabi-v7a too 😉.

I saw only very limited and outdated devices for x86 and x86_64 platforms.
But can see lots of armeabi-v7a devices in Playstore device catalog.

**Comment by cherryleafroad** [comment]
I'm afraid I haven't yet been able to get armeabi-v7a to build without errors yet. Probably some of the source code needs to be altered to support it, plus some changes to the build system. Sadly, I don't have time to fix / test the source code in all the support libraries and such. It took a lot of custom source code fixes just for armv8

**Comment by androsparks** [comment]
@cherryleafroad 
Any way its a great work 👍. I will let you know if i am able to build armv7

**Comment by cherryleafroad** [comment]
If you're able to tell me what worked for you and what didn't, it'd definitely help me narrow down what is broken or not. Good luck!
