### ISSUE TITLE
Still no Implementation

### ISSUE THREAD

**Issue by swa00** [cherryleafroad/Android-ImageMagick7#9]
Hi,

at  first  -  Thx  a lot  for  your work ...
I  do not have  experience  with  NDK  and  i need  the  Lib  only  for  one operation in my  app ( bevel)

But  im Sorry ,  maybe  i'm stupid -  i  followed all instructions with  the finished zip  from here
https://github.com/cherryleafroad/Android-ImageMagick7/issues/4#issuecomment-568859199

i still  get no Unsatisfied Link  error.  Can  you pls help  me ??

What  i  have done 

a) create  a  blank project ( androidx , AS 4.1.1)
b) copied  the  whole Source, created  a (blank) Jni folder,
c) created  a libs/arm64-v8a and  copied all files  from zip above into it
d) compile  project ( with NO  changes  of  init part  in your  Mainactivity )
f)  added Write  permission

When  i  start  the  project ,  the  lib  will  loaded ( System.loadLibrary("jmagick-7");

But the  next  point  fails 

java.lang.UnsatisfiedLinkError: No implementation found for void com.wdtec.testapp.magick.Magick.setAppConfigDataDir(java.lang.String) (tried Java_com_wdtec_testapp_magick_Magick_setAppConfigDataDir and Java_com_wdtec_testapp_magick_Magick_setAppConfigDataDir__Ljava_lang_String_2)

Any  cool tip as  christmas  gift  for  me ? :-)

Thank  u  very  much

**Comment by cherryleafroad** [comment]
Did you follow the Quick Setup Instructions on the main page, including the section on How to Run the Binary, and the FAQ of Frequently most encountered problems? There's even a link to an example app with example code.

**Comment by swa00** [comment]
Dear Cherry ,



as  first -  THANK  you  very much for  your (long) answer and  your  time  you spent for it.
While i  try to understand completly your  answer  and get into it,  as  attach  my cleaned project

**Comment by swa00** [comment]
.

**Comment by cherryleafroad** [comment]
> i think also, that i do not understand correctly , whats the different between the versions and
> what IM source-code has to use. to build

As usual, new versions offer bug fixes and newer features.

**Comment by cherryleafroad** [comment]
So some things I noticed with your project.

- In your `build.gradle`, you don't have `sourceSets` or `splits` inside `defaultConfig`.
- `libs` folder is fine, but like I said before, you should be using the binary version. Using only shared libs without a binary isn't going to be that useful for you.
- You can place the `jni` folder with all the source of the project at the same level of your `build.gradle`, `libs` and `src` folders. [Reference](https://github.com/cherryleafroad/Android-ImageMagick7/tree/master/libjmagick-7/android/app)
- You need the `assets` folder for things to work properly. [Reference](https://github.com/cherryleafroad/Android-ImageMagick7/tree/master/libjmagick-7/android/app/src/main)
- You're missing the `fakewt` and `magick` support Java libraries. They're placed at the wrong folder level. See in the [reference](https://github.com/cherryleafroad/Android-ImageMagick7/tree/master/libjmagick-7/android/app/src/main/java) the level they're at. `app/src/main/java/awt` and `app/src/main/java/magick`. Not that you'll need those though, that's only for the jmagick version, which you should be using the binary version anyways (no need for those libraries after that).
- `MainActivity,java`, as I said before, after getting the binary only version (and you should build it yourself too), you also need to check the code and uncomment /delete the proper sections, and configure it to what you need:

Uncomment section:
```
        /* CODE FOR SETTING UP BINARY USAGE
           Obviously you will need to check whether you already set this up or not
           You don't want to run this every time you start your app
           You can use Android SharedPrefs to keep track of it
```

Delete section:
```
        // FOLLOWING CODE EXAMPLE BELOW IS FOR JMAGICK ONLY. IF YOU DON'T USE JMAGICK, 
        // USE THE BINARY CODE ABOVE ONLY
....
    /// END JMAGICK SECTION
```

Uncomment section
```
    /* AsyncTask example code used for executing the binary
       If you don't run the binary on a separate thread, your UI will freeze
       Adapt it to your needs
```

... And so on

- And build it from source so you can use the latest.
- - Install ndk from the sdk manager.
- - Copy all project files into `project/app/jni` and run `build-release.bat`. Building only works on Windows.

**Comment by swa00** [comment]
Thank  you  - very  much :-)

I started  to  get  into  it  -  this  will  take  the  night  and  i  will give  you  the  feedback
(Hopefully  happy  .....  or  i will change  my  proffession next  year)

**Comment by cherryleafroad** [comment]
`Java_com_wdtec_testapp_magick_Magick_setAppConfigDataDir`
This error means that Java is looking for the native function in JNI, but it can't find it. Notice the path `com_wdtec_testapp_`. In short, your packages are in the wrong places.

My C functions are named `Java_magick_Magick_setAppConfigDataDir`, which you can see the Java package path here `magick_Magick`. [Reference](https://github.com/cherryleafroad/Android-ImageMagick7/blob/master/libjmagick-7/src/magick_AppDataDir.c)

So, if you fix your package locations, it'll fix that

**Comment by swa00** [comment]
>>This error means that Java is looking for the native function in JNI, but it can't find it. Notice the path >>com_wdtec_testapp_. In short, your packages are in the wrong places.
>>So, if you fix your package locations (and the package statements and import statements), it'll fix that error

Oh, my, god !!!!
This  was  the  goal and its working !!!
Note for me in the future  :  Leave it like it  is and don't think to much  :-)

@cherryleafroad

Thank you  very much for  your  help.
i wish  you and your family a nice christmas time and please keep healthy

**Comment by cherryleafroad** [comment]
You should know that the jmagick version is probably unreliable too, I wouldn't trust it much to do what it should.

**Comment by swa00** [comment]
yes  you  wrote  this  sometimes  above .... and  i'm  c developer -  the  work  ist  too  much  ......
But  as  i  see  it  , its  the  only "usable" Imagelib to  do simple processes.

in my  case, i only  need  a bevel function like "EmbossMaskFilter" from the  original Google  API.
But this filter  was  removed ( deprecated ) since  API 28 without  any replacement or  comment  from Google.
(How often at google :-()

Therefore  i  tried  OpenCV and  ImageMagick .
But  if  you  have  any  other alternative ,  or  idea -  let  me  know.

**Comment by cherryleafroad** [comment]
I mean the binary version. It's much easier to do something like what you what from the commandline ;)

**Comment by swa00** [comment]
i  also found  something  in this  direction

https://github.com/thenewcircle/renderscriptimaging

Its  working (and  fast) , but  you have  to step  deeply  in  impageprocsing  from scratch , to implement
all  basic  functions -  same  work  to  re-develop  any  c-library

**Comment by swa00** [comment]
Beside Note : Playing  with  your  implementation ,  i  found  out  that an Android - bitmap operation is  missing.
e.g  getting the  BGRA pixels an transfer  them  to ARGB. (or just  get  an Bitmap Object during runtime)

Ref :
https://github.com/paulasiimwe/Android-ImageMagick/blob/master/jni/magick_MagickBitmap.c

**Comment by cherryleafroad** [comment]
> Beside Note : Playing with your implementation , i found out that an Android - bitmap operation is missing.
> e.g getting the BGRA pixels and transfer them to (int) ARGB. (or just get an Bitmap Object during runtime)
> 
> Ref :
> https://github.com/paulasiimwe/Android-ImageMagick/blob/master/jni/magick_MagickBitmap.c

Yet another thing missing from the [official project](https://github.com/techblue/jmagick/tree/master/src/magick). Another example why I don't trust jmagick support, as it's quite lacking.

**Comment by swa00** [comment]
Thx  a  lot :-)  

in the moment  i'm  trying  to  figure  out  ,  how  to  setup  the  system  correctly  to  use  NDK  .
As  i  wrote  above , i  never  played  with  NDK  .

Do you have  time  to  recomplie the  binaries and  place  them here as  ZIP ? 
(If  not  -  no  problem  -  it  just saves time -  it  is  only  a question)

**Comment by cherryleafroad** [comment]
I don't - I haven't done this project in a long time and don't have things set up anymore. But if you encounter errors and need additional help, feel free to let me know and I'll help you out. My discord is Selena'sBabe#2978. I'm closing this issue as the original problem is solved.

**Comment by swa00** [comment]
Using  the new  NDK  22.070, you have  to change  several  things

a) /MagicCore/memory.c -> function AcquireAlignedMemory_STDC (Line 252)
Because  "align_alloc"  is  obsolte  ... change 
`return(aligned_alloc(CACHE_LINE_SIZE,extent));`
into
`void *ptr = NULL;
  posix_memalign(&ptr,CACHE_LINE_SIZE,extent);
   return ptr;`

b) 
Batchfile needs  some  changes 

-during batch compiling error "fcntl(): Bad file descriptor"
NDK needs to  disable parallel processing with the flag "--output-sync=none"

- With Win10 the  settings of  envoirments does  not  work,  so  the  ndk_build  needs full  pathes

Full Example
`ndk-build --output-sync=none NDK_PROJECT_PATH=[YOUR_PATH_TO_Android-ImageMagick7-master] NDK_APPLICATION_MK=Application.mk APP_BUILD_SCRIPT=Android.mk NDK_OUT=../build/ NDK_LIBS_OUT=../jniLibs -j 4
`
